### ISSUE TITLE
Migration Tracker

### ISSUE THREAD

**Issue by sciabarracom** [apache/openserverless#2]
- [x] Setup the development environment
- [x] https://github.com/apache/openserverless/issues/3
- [x] https://github.com/apache/openserverless/issues/4
- [x] https://github.com/apache/openserverless/issues/5
- [x] https://github.com/apache/openserverless/issues/6
- [x] https://github.com/apache/openserverless/issues/7
- [x] https://github.com/apache/openserverless/issues/8
